language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: i3jaKwLs6uR17ZlorwV1NGwh6Z2XCXLEMmz5PdTh70iYLBa6C29cGgY/IfCvLN9fH4tamw5ZKg920hLTcmOg7hqSBFM6l/4xMTKH9dKMF1yLdUVWihOJmvoGsrgZcJxRJ4VoHdATrOooO8NX1LRUb/0sLhbJZ+3UMRP4npfU8kN2Zy2k5caEfrd5ANQO6E9O7N7VJ+1GKY69rHRSULN6rpe50MwdL1/vZa2eqVdzGNZhva/peW14mkN0TGEqNx2uOtlz0/e4h7OKfhRd8IEuUOaC7IUDAZZBkIsx0wQB7uO+vHmaYffO4Bnfp5eQcdJJvSXcO7bwgS3eFSLgoNNgju4dv9w9AL8apPMCvSMSjcekGVlwXJNSzL8gdU66Nx6fmlAueamCmFno8aQGIo4prBuQCT0tMSUa+vXFwRcAI/Uj+Z1bNksxh025EW5OkXyRiRXpNZHrBeIz35xK5Dcfnj1kljNyZV7/M+j+mJDn+FSasFDn5mqu/1Xs8Rth+gydfBdQ9YNYj4Z0GKlV4zxXH8OtmnHq4osY+X1VBVoXgXv15EcvFRyXSucPyFkb7Fgmge2lG/bB9wh4P6y4XTkybp8QySYY+Lx64lO6ML0I+md2JYSjBFogYLoY/JqYqcAd2jHOWw/J1rUcHsKSViviHWmToLrhTzl41El2hptuWRM=

